### ISSUE TITLE
Questions about optional params

### ISSUE THREAD

**Issue by beckula** [atotic/excess-router#10]
Hi Aleksandar,
Thanks for creating excess-router - it's a great idea.  I'm running into an issue though.  I have "pages" in my Polymer app (managed by iron-pages), and a number of optional parameters that I'm trying to get to co-exist in one or more routes.

There will always be a page parameter in my route along with zero or more optional parameters.  The optional parameters build on each other, so the second parameter can't exist without the first, and the third can't exist without the second, and so on.  For the sake of this example I'm showing two optional parameters.

I tried a few different excess-route options.  First I tried individual routes representing each possible URL.  For example:

``` html
<excess-route route="/:page"
    page="{{selectedPage}}"></excess-route>

<excess-route route="/:page/:product"
    page="{{selectedPage}}"
    product="{{selectedProduct}}"></excess-route>

<excess-route route="/:page/:product/:mode"
    page="{{selectedPage}}"
    product="{{selectedProduct}}"
    mode="{{selectedMode}}"></excess-route>

<!-- catch unknown routes and redirect to mypage -->
<excess-route route="/(.*)"
    redirect-to="/mypage" activation-modifiers="x"></excess-route>
```

With this approach I can visit URLs `http://localhost/#/mypage` and `http://localhost/#/mypage/myproduct`.  If I visit the `/mypage/myproduct` URL and I modify selectedProduct in the UI it updates the URL - great.  However, if I visit the `/mypage` URL, and I modify selectedProduct (in this case from null to a value) nothing happens.  I was hoping it would pass over the first route, match the second route, and change the URL to `/mypage/myproduct`.

Then I tried a single route with multiple optional parameters.  I kept the parameters in order, since they build on each other.

``` html
<excess-route  route="/:page/:product?/:mode?"
    page="{{selectedPage}}"
    product="{{selectedProduct}}"
    mode="{{selectedMode}}"></excess-route>

<!-- catch unknown routes and redirect to mypage -->
<excess-route route="/(.*)"
    redirect-to="/mypage" activation-modifiers="x"></excess-route>
```

This worked much better.  I could navigate to `http://localhost/#/mypage`, then select a value for selectedProduct and see the URL automatically change to `http://localhost/#/mypage/myproduct`.  Same thing for mode.   However, there are two interesting side effects.  

1) When I load the page using this route, although my property values (selectedProduct, selectedMode) are initialized to null in Polymer, Excess Router changes makes them all undefined if they're not present in the URL.  

2) When I use iron-pages to change pages, any missing optional parameters are added to the URL as /undefined.  So if I visit URL `http://localhost/#/mypage1/myproduct`, and I switch to mypage2, the URL becomes `http://localhost/#/mypage2/myproduct/undefined`. undefined is the selectedMode property.  It was not present in the first URL.

I'm probably missing something, or configuring incorrectly. What do you think?
Please let me know if you want more info or larger code samples.

Thanks!

**Comment by beckula** [comment]
Oh interesting thing to note.  The values aren't being set to undefined - they're being set to the string 'undefined'.  (value of selectedMode is undefined;  typeof selectedMode is string).

**Comment by atotic** [comment]
Glad to hear you are figuring out how to use it correctly.

>  1) Router changes makes them all undefined if they're not present in the URL. 

This is expected behavior.

> 2) When I use iron-pages to change pages, any missing optional parameters are added to the URL as /undefined.

That's a bug, and probably an easy fix.

> . I was hoping it would pass over the first route, match the second route, and change the URL to /mypage/myproduct.

Only active routes react to attribute changes. If inactive routes reacted to attribute changes, you could end up with accidental navigation.

**Comment by atotic** [comment]
You were right about values undefined, that was the core bug. decodeUriComponent returns 'undefined' when arg is undefined. Fixed in master, will ship in the next release. I do 1 a week if needed.

**Comment by beckula** [comment]
That's great, thanks for the update.  Pulled and tested - everything looks great.  No more 'undefined' params in the path.
