### ISSUE TITLE
Best way to handle nested routes with lazy pages?

### ISSUE THREAD

**Issue by urandom** [atotic/excess-router#11]
I'm trying to use the routing with a bunch of components that are only supposed to be loaded when needed.  My main page has the toplevel route which decides what to load, and each lazy page is supposed to have its own set or routes. For examples:

```
top: 
    /:toplevel/(.*)?
lazy one:
    /lazy1/:foo
    /lazy1/:foo/bar/:test
lazy two:
   /lazy2/:bar
....
```

Right now I have the lazy routes within their lazy parents, and they are loaded using that lazy-pages link hack, so they aren't present immediately. However, this way they aren't evaluated. I assume it is because they've been created after the route manager has been started.

So what's the proper way of creating such a hierarchy?
One way I can think of is to define all the routes at toplevel, but that would mean that I will have to pass about a ridiculous amount of parameters to the lazy components. That would make the html part quite unreadable. And I don't think the toplevel component should know the specifics of how inner components navigate.
Is there any other way? Or perhaps a way to make dynamically created routes work with a manager that's already started?

**Comment by atotic** [comment]
Dynamically created routes should work. What do you mean by not evaluated?

**Comment by urandom** [comment]
I mean that, for example, one of the lazy routes which should definitely match when the page is first loaded and the lazy page is loaded with it should be set to active. It's not. And none of the related parameters are evaluated with it (probably due to it not being 'active'), which leaves the component containing said route with undefined properties tied to these parameters.

**Comment by atotic** [comment]
Can you show me a reproducible case?

**Comment by urandom** [comment]
Unfortunately I can't reproduce it with a simpler case.

**Comment by atotic** [comment]
Complex case works too, just something I can run locally. I suspect the cause is something about your route configuration. I've seen heavy use of dynamically inserted routes without problems.

**Comment by urandom** [comment]
I'll have to look more closely at what differs between my simple case and the real thing. The real thing is basically this:
The lazy pages and top level route:
https://github.com/urandom/readeef/blob/migrate-to-polymer-1.2/templates/components/rf-router.tmpl#L61

The inner component with its own routes:
https://github.com/urandom/readeef/blob/migrate-to-polymer-1.2/templates/components/rf-feed-base.tmpl#L105

In the later, the 'tagOrId' property is never set when the initial url points to it, and the route itself is never marked as active.

Its strange that it's not that different from the simple case I wrote, yet it doesn't work.

**Comment by atotic** [comment]
I've noticed that that you are using `<link rel=import` tags in your lazy-pages. This used to work, but is depreciated, since it does not work in all browsers.
If you have your code live somewhere, I can take a look.
