### ISSUE TITLE
Parameter with slashes

### ISSUE THREAD

**Issue by MajorBreakfast** [atotic/excess-router#13]
Thanks for building this lib. It works great so far!

I'm using the router as follows in my app.

``` HTML
<excess-route route="/catalog/:path(.*)?" path="{{path}}"></excess-route>
```

I've got catalog `path`s that contain slashes. Unfortunately the lib escapes those. Everything still works, the URL just looks a bit messy. Example URL:

```
http://localhost:8000/#/catalog/folder1%2Ffolder2
```

Instead of:

```
http://localhost:8000/#/catalog/folder1/folder2
```

Any idea how I can fix this?

**Comment by atotic** [comment]
'/' is a path separator, so it has to be escaped. You can separate your path into multiple components:

```
<excess-route route="/catalog/:path?/:subpath?" path="{{path}} subpath="{{subpath}}"></excess-route>
```

and that would make your urls look better.

**Comment by MajorBreakfast** [comment]
But this limits how deep my path can go. It's a folder structure, so I don't really have a hard limit there. Any ideas how I can make it work?

**Comment by atotic** [comment]
The path argument will always be escaped. To make your paths look pretty you'd have to do the navigation yourself (ExcessRouterManager.transitionTo(/catalog/folder/folder). Your bindings will get a bit messy, you'd have an extra navigationPath variable that you use to do manual transitions, and you'd observer path, and set navigationPath = path whenever path changes.

**Comment by MajorBreakfast** [comment]
Ha! Perfect. Feels a little hacky - but it's a one-liner :) I added this in the event handler:

``` JS
Excess.RouteManager.transitionTo('/catalog/' + path)
```

Thx!
