### ISSUE TITLE
Anchor clicks sometimes aren't caught

### ISSUE THREAD

**Issue by urandom** [atotic/excess-router#14]
Hi,

Sometimes the clicks on an anchor aren't being executed through the route manager, and instead do their default behavior. That's because the expression in the following line is false:

https://github.com/atotic/excess-router/blob/13339ffc6902b8bd1ade184da70237812115c613/excess-route-manager.html#L715

The reason being that the target is actually a descendant of the anchor, not the anchor itself. The code should instead probably check all the nodes along the dom tree, starting with the target, to try and find an anchor.

**Comment by atotic** [comment]
Patch happily accepted. I have not been around this code for a while.

**Comment by urandom** [comment]
Ok, I'll whip out a fix
