### ISSUE TITLE
Anchor handling erroneously 'handles' links outside the scope of the registered routes

### ISSUE THREAD

**Issue by urandom** [atotic/excess-router#15]
Hi,

It looks like the manager initiates a transition based on the anchor's link, even when the link is completely outside any known route scope. This is easily observable when a link points to a completely different domain, but it looks like it will most likely incorrectly try to route even when the link just points somewhere else in the same domain (say, outside the manager's base path, or outside any of the registered routes' paths). The later case might be important if you have a link that you want the browser itself to handle within your domain, like if you want to go to a different SPA on the same server.

**Comment by atotic** [comment]
I've never used this feature. The magic happens here:

```
     _routeAnchor: function(anchor) {
      if (anchor.protocol === 'javascript:')
        return false;
      var route;
      switch(RouterState.pathStyle) {
        case 'hash':
          route = anchor.hash;
          if (StringStartsWith(route, RouterState.hashPrefix)) {
            route = route.replace(RouterState.hashPrefix, '');
          }
          break;
        case 'path':
          route = anchor.pathname;
          if (StringStartsWith(route,RouterState.basePath)) {
            route = route.replace(RouterState.basePath, '');
          }
          break;
      }
      if (route) {
        try {
          this.transitionTo(route);
          return true;
        }
        catch(err) {
          console.warn('anchor route not found', route);
          return false;
        }
      }
      return false;
    },
```

If you think excess-router should do something different, patch requests happily accepted
