### ISSUE TITLE
Can't get sub-routes to render

### ISSUE THREAD

**Issue by dominicglenn** [atotic/excess-router#2]
In the example, you can have a route and a sub-route and match each one so that you can show either a `list` view or a `detail` view; however I cannot get this functionality to work locally.

The following code never shows any template at all; the only way I can get it to show is by navigating directly to the `detail` view, and then the `list` view works correctly when navigated to (as if the variable has now been set to `false` correctly).

```
<section data-route="users">
  <excess-route route="/users/:userId" user-id="{{userInfoUser}}" active="{{userDetail}}"</excess-route>
  <template is="dom-if" if="{{!userDetail}}">ListView</template>
  <template is="dom-if" if="{{userDetail}}">Detail View</template>
</section>
```

The only way I can get it to work locally, is to set a variable for both the `detail` view and the `list` view, like the following:

```
<section data-route="users">
  <excess-route route="/users" active="{{userList}}"></excess-route>
  <excess-route route="/users/:userId" user-id="{{userInfoUser}}" active="{{userDetail}}"</excess-route>
  <template is="dom-if" if="{{userList}}">ListView</template>
  <template is="dom-if" if="{{userDetail}}">Detail View</template>
</section>
```

Am I doing something wrong? Do I need to set the variable `userDetail` to `false` by default somewhere in my javascript?

I'm using Polymer 1.1.0

**Comment by atotic** [comment]
The problem was that excess-route.active was not being initialized to false. And Polymer does not propagate bindings until they are set, so your template if binding never fired. 
I've fixed it in the master, want to try it out? I try to cut releases on Friday, rolling up all the weekly bug fixes.

**Comment by dominicglenn** [comment]
That change seems to have solved the issue that I was having. Thanks for that!

**Comment by atotic** [comment]
great, if you have any other problems, fire away
