### ISSUE TITLE
transitionStyle seems to be ignored (history.pushState is never called)

### ISSUE THREAD

**Issue by web-padawan** [atotic/excess-router#21]
I try to use router config with `path-style="path"` in order to keep existing routes of my project.
However, history.pushState seems not to be called: when I press "Back" button in browser, I'm just thrown out of my SPA at all, instead of walking through previous instances.
Neither is it called when I add `transition-style="transition"` attirbute to each route.
I've detected that references to `this.transitionStyle` are only inside `_navigateToAttributes` method which isn't called (at least, `console.log`inside isn't reached).

**Comment by web-padawan** [comment]
UPD: it seems that the true reason is middleware url rewriting (koa.js).

**Comment by atotic** [comment]
Do you have an example I can see? pushState is called when transition completes. Are you triggering a transition?

**Comment by web-padawan** [comment]
I pasted some real routes into my [sandbox project](https://github.com/web-padawan/polymer-sandbox). 
Please follow instructions in readme to run it. Routing is described [here](https://github.com/web-padawan/polymer-sandbox/blob/master/src/components/core/bi-router/bi-router.html).

**Steps to reproduce:**
1. Open http://127.0.0.1:8100
2. Go to the "settings" page (you will be redirected to settings/general)
3. Hit "Back" button in browser or keyboard - you will not be moved to "home", as it is desired, but thrown out of the app (in my case - to the empty browser tab).

I've also noticed that:
a. When I remove redirecting route from the chain, history api is OK (and "Back" button works).
b. When I open first http://127.0.0.1:8100/settings, then go to home page - "Back" works too!

So, it seems that something is wrong with redirects.
BTW, what does it mean `aborted: true` inside of `event.detail.transaction`? Maybe it is related?

**Comment by atotic** [comment]
Can you make me a version where excess-router runs unminified?

**Comment by web-padawan** [comment]
It's done, check my latest commit.
I also added some debug output for [connect-history-api-fallback](https://github.com/davezuko/koa-connect-history-api-fallback) in local-web-server.
So please also run `npm i` again.
**UPD:** added another redirect for "home" page too.

**Comment by atotic** [comment]
You are getting "not found" pages from your server. It does not recognize /ui/settings urls, etc. 

When I switched routing to path everything worked correctly. I think the problem is on your end, unless there is a bug in path routing that does not exist with anchors. If there is such a thing, it'd be in handling of anchor clicks....
