### ISSUE TITLE
IE11 / Microsoft Edge not reacting to uri change

### ISSUE THREAD

**Issue by Compufreak345** [atotic/excess-router#6]
It's me again ;) 

I just tried your router in IE11 and edge and it works, except for the case where I just modify the URI by setting document.location.href="#/something" or by changing it by hand - in Chrome, Firefox and Safari the parameters get refreshed, in IE11 and Edge they don't. I hope you find a solution for this.

Here is an example : http://output.jsbin.com/nojuhu#/Change%20me!! - The second button works for changing param 2, the first does not. Also, changing the URI by hand does not work.

Source : http://jsbin.com/nojuhu/edit?html,output

Best regards,
Christoph

P.S.: I put a timeout of 5 seconds for loading, otherwise I had some issues with Polymer not being found...

**Comment by atotic** [comment]
I have a feeling that this is an IE bug, they probably do not fire hashchange event. If that's the case, you'll need a workaround.

PS:
Polymer not found: of course, because it loads asynchronously. You should listen for WebComponentsReady event instead of timeout.

**Comment by atotic** [comment]
Found the cause, IE does not fire popstate when only hashchange happens. Chrome etc fire both. Working on a workaround...

**Comment by atotic** [comment]
Fixed it on master, reopen if it fails

**Comment by Compufreak345** [comment]
It works very well - thank you! 

P.S.: A release would be cool so I could switch from my fork to your well maintained version again ;)

**Comment by atotic** [comment]
Done. In the future, you can always point to atotic/excess-router#master for the latest.
