### ISSUE TITLE
Passing additional attributes

### ISSUE THREAD

**Issue by go4cas** [atotic/excess-router#8]
When I used page.js for routing in the Polymer Starter Kit, I could do something like:

``` javscript
    page('/orders', function() {
      app.route = 'orders';
      app.title = 'Order Management';
    });
```

So, I would be able to set an attribute on the app object, when changing the route, which I used to display in the header of the app.

How would I be able to achieve similar functionality with <excess-router>?

**Comment by atotic** [comment]
Have you looked at the demo Navigation section? It enumerates all the ways to navigate.

http://atotic.github.io/excess-router/components/excess-router/demo/index.html

**Comment by go4cas** [comment]
HI Aleksandar,

Yes, I did. But, I couldn't find anything that's specific to what I'm
looking for. Would you suggest I build this logic into one of the routing
events? If so, where would be the best place to add this?

Thanks,
Cas

**Comment by atotic** [comment]
something like this?

```
<dom-module id="my-app"><template>
    <excess-route route="/orders" isActive="{{ordersActive}}"></excess-route>
</dom-module>
Polymer({
    is: 'my-app',
    properties: {
       ordersActive: { type: Boolean, observer: 'ordersChanged' }
    }
   ordersChanged: function() {
      this.route = 'orders';
      this.title = 'Order Mgmt';
   }
});
```

But that's verbose and not pretty to look at. If I was doing it, I'd try to be more Polymerish:

```
<dom-module id="my-app"><template>
  <excess-route route="/:mainmenu" mainmenu="{{route}}"></excess-route>
</template></dom-module>
Polymer({ is: 'my-app',
    properties: {
      route: {
        observer: 'routeChanged'
      }
    },
    routeChanged: function(route) {
        switch(route) {
          case ''/orders": this.title = 'Order Management'; break;
          etc......

```

```
    }
}
```
