### ISSUE TITLE
Exposing RouteManager._findDestinations

### ISSUE THREAD

**Issue by urandom** [atotic/excess-router#9]
Would it be possible to promote '_findDestinations' to a more 'public' status, i.e. dropping the leading underscore? I prefer to construct my links using route aliases and parameters, and I found the destination path to be exactly what I need. The only problem is that the only way I can obtain that is by calling _findDestinations, but that doesn't seem to have been intended for public consumption.

**Comment by atotic** [comment]
`_findDestinations` returns route objects, which I was hoping to keep private. Can you give me a source code example of how you are 'constructing your links'? I'd like to figure out what the best API to handle your use case is.

PS: any other comments about the router? Was it easy to pick up?

**Comment by urandom** [comment]
For the _findDestinations, I don't really need the routes right now. Just the actual path. I basically have a function that is supposed to return anchor hrefs, and I want to keep the whole thing clean by constructing urls using route aliases and parameter values.

So far I can't really comment on the router itself, I've only spent one hour looking at it. I'm trying to move away from more-routing since it was deprecated and doesn't work anymore, and so far excess quite a bit different. I can only comment on what I miss from more-routing the most up until now. One of the things is an equivalent for 'urlFor', which is basically what this bug is about :) 
Another thing which is not major in any way and I'm working around is being able to ask the route manager for a route object when I give it an alias (and optional parameters), so I can check whether its active, for instance. Right now I'm working around that by basically having an additional route per level (i.e.: route="/:toplevel" toplevel="{{ topLevelNav }}"), and checking the value of that instead (while still having specific routes, such as '/settings', '/foo', '/bar', so that I can navigate to them and build urls for anchors using their aliases). And that's probably better in the long run anyway, but it might still be a good idea to be able to query routes from the manager.

**Comment by atotic** [comment]
> 'so that I can navigate to them and build urls for anchors using their aliases'

You can just use aliases in anchors like this:

```
<excess-route route="/main" name="top"> 
<a href="@top">
```

urlFor can be computed from a route string like this:

```
function urlFor(path, params) {
    pathToRegexp.compile(path)(params);
}
```

Not sure whether exposing this as a method is useful. I feel that it is an anti-pattern, something you should not be doing if you were using the router correctly.

The philosophy behind the router is that you declare your routes once in excess-route, and then query those routes for their active status, and use them to navigate.

more-routing approach was different, and I felt it was needlessly complex. If you have a good example why you need urlFor, I'll reconsider adding the api.

**Comment by urandom** [comment]
Didn't know about using aliases in anchors directly. How do you pass the parameters to them?

Btw, urlFor is more useful with aliases. From what I understand, pathToRegexp expects a proper url with param placeholders. Whereas urlFor can also do the equivalent of: `urlFor('@top', {top: 1})`

> The philosophy behind the router is that you declare your routes once in excess-route, and then query those routes for their active status, and use them to navigate.

That sounds like a good approach. However at first glance I didn't see a way to query for any registered route through the manager, in any publicly exposed way. I assume currently the only 'proper' way of doing it is to actually query for the route elements in the dom.

**Comment by atotic** [comment]
> Didn't know about using aliases in anchors directly. How do you pass the parameters to them?

No way to do this. You can make your anchors use javascript in that case:
`<a href="javascript:ExcessRouter.navigateTo('@top', { top: 1})">`

The philosophy is that once you define a route, you should not need to know its url. The url can go stale as app mutates.

The only scenario I can see where you would need to know the url is if you have no other choice: for example, a router-unaware external library that requires full urls. And for this use case, I can create an API. How about this:

```
RouteManager.getRouteUrl(path, params)
```

**Comment by urandom** [comment]
> <a href="javascript:ExcessRouter.navigateTo('@top', { top: 1})">

I find using the 'javascript:' schema rather ugly tbh. It also reduces the usability of the link quite a bit. If you go with that approach, your anchor is stuck in that window. You can't open a new tab, you can't go incognito with a link, you can't share that link over email, etc. The same is true if you use an 'onclick' and a callback. The only useful anchors are ones that contain proper urls. Which is why it's essential that its easy to 'convert' aliased routes and parameters to proper urls.

> RouteManager.getRouteUrl(path, params)

This looks good, as long as 'path' can also be the alias.

**Comment by atotic** [comment]
I get it, good for you for thinking of right-click anchor usage. I've added getRouteUrl to Routemanager
